version: "2.4"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7.25
    volumes:
      - ./sql-data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    hostname: VIP
    environment:
      MYSQL_DATABASE: 'test_database'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'admin123456'
      MYSQL_ROOT_PASSWORD: 'admin123456'
      MYSQL_ROOT_PASSWORD: 'admin123456'
